### ISSUE TITLE
Roland Appears to have migrated to Linux

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rpbouman/kettle-cookbook#46]
```
Create ${OUTPUT_DIR} and Copy Template step has some home directory stuff 
hardcoded as yourself.

I tried to swap it out for my defaults but when i did it didn't create toc.html 
or frontpage.html


```

Original issue reported on code.google.com by `tom.bar...@meteorite.bi` on 14 Feb 2012 at 9:11

**Comment by joaociocca** [comment]
Tested both on Windows 8 and Debian, no problems found. Index, toc and frontpage created as they should. Could this be related to #47?
