### ISSUE TITLE
Cookbook doesn't product html output on MacOSx with PDI 4.4.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rpbouman/kettle-cookbook#60]
```
What steps will reproduce the problem?
1. Ran kitchen.sh with input and output dirs 
2. Job runs and shows it is processing files and directories - including 
successful generation of index.xml files
3. Doesn't seem to run the transform scripts because there is no html output at 
all - html directory in output dir is empty toc.html and frontpage.html are 
missing too

Try to debug a bit, seems like it doesn't generate a FULL_TRANSFORM_SCRIPT file 
at all.

See attached debug log if that helps.  I'm running the latest trunk to fix the 
issue with multiple saxon jar files.

```

Original issue reported on code.google.com by `malsm...@treehousesystems.com` on 16 Aug 2013 at 9:02

Attachments:
* [cookbook.log](https://storage.googleapis.com/google-code-attachments/kettle-cookbook/issue-60/comment-0/cookbook.log)

**Comment by joaociocca** [comment]
hey @rpbouman, should we close this? I don't think backwards compatibility to 4.x should be an open issue anymore. If anyone can test a current build of the cookbook with PDI 5.x, and it continues to have this problem, that'd be another issue, right?

**Comment by rpbouman** [comment]
@joaociocca You're right. Thanks!
