### ISSUE TITLE
cookbook for kettle 5.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rpbouman/kettle-cookbook#67]
```
Hi.
I made some modifications on ktr files in order to work with kettle 5.1.0.0-752 
(mostly mapping steps).

Attached patch versus revision 87.

Hope this can be useful for other peoples.

Best regards.

Enrico
```

Original issue reported on code.google.com by `enricomariam42` on 8 Sep 2014 at 10:59

Attachments:
* [cookbook-kettle5.patch](https://storage.googleapis.com/google-code-attachments/kettle-cookbook/issue-67/comment-0/cookbook-kettle5.patch)

**Comment by filipegatti** [comment]
I'm kinda new to using git, but I believe your patch has a lot of paths pointed at your personal directories, so I wasn't able to apply this patch in my version. Did you do a lot of changes to the transformations? Maybe you could share what you did?
