### ISSUE TITLE
running kettle-cookbook with kettle 6.1

### ISSUE THREAD

**Issue by JanPit78** [rpbouman/kettle-cookbook#72]
Kettlle-cookbook doen't work with kettle version 6.1.
It look likes the generation of the sub directories won't work in the target of the documentation and ${FULL_TRANSFORM_SCRIPT} seems to be empty

**Comment by joaociocca** [comment]
I need to check this - unless @rpbouman can get to it first... but I remember running kcb this week on 6.1 without any errors (except from the warning message about xslt processor)

**Comment by rpbouman** [comment]
@JanPit78 how did you obtain cookbook? I have not prepared a downloadable distribution for a long while. Recommended way to use cookbook is to dowload the entire project as a .zip, or to clone the repository.

**Comment by JanPit78** [comment]
I dowload it as a zip file. put it into a directory en run document-folder.kjb. Thats all

**Comment by cosmocracy** [comment]
I'm interested in this issue--currently use PDI community edition and just now starting to dabble with the autodocumentation in Spoon.  Would like to try KCB so if there are issues with it and 6.1, I would be happy to lend assistance.  (I am an experienced Java and ETL developer though still learning PDI.)

**Comment by TTassoni** [comment]
Hi, I had same issue of JanPit78. I use pentaho CE 6.1, downloaded zip file from here, put it in a directory and run document-folder.kjb. I tried to run it either from GUI and kitchen.

**Comment by rpbouman** [comment]
Hi All,

people, I'm sorry to say I don't have the time to look into this. I am currently not using PDI or cookbook, and I can't make the time to maintain this. 

So, please, use your troubleshooting skills and try to fix it. I'll be happily accepting your pull requests. I done my bit in creating and maintaining cookbook for a good number of years. It's time someone else stepped up to the plate. Thank you.

**Comment by carteramandaj** [comment]
@rpbouman, I created a pull request with the fix.

@JanPit78 & @TTassoni , If you don't want to wait for the PR to be accepted: 
- Open compare-files.ktr
- Open the Select/Rename values step "output-dir -> dir"
- On the Remove tab, add the field "dir"

That should fix the issue.  I found that one of the best ways to troubleshoot nested mappings is to write the mapping input fields to the log (Write to Log step).  It made it plain to see that the get-files.ktr step was using the wrong directory value.

**Comment by blijblijblij** [comment]
👍

**Comment by rpbouman** [comment]
@carteramandaj Amanda, thanks! Much obliged :) Merged. @JanPit78, @TTassoni, could you do your bit and please test it and let us know if that resolves the issue? Would be really cool to let Amanda know and give her a tank you and a thumbs up if that fixes it.

**Comment by JanPit78** [comment]
I did a little test and for me with a good result. Amanda thanks a lot for fixing this issue.
Great work!

**Comment by rpbouman** [comment]
Hi @JanPit78 , 

thank you for checking! @carteramandaj, thanks again for your contribution. I'm going to close the issue and mark as fixed.

**Comment by TTassoni** [comment]
Great job, Amanda! I was working in the same direction (putting write to log step inside transformations). I made a test. I confirm that html files are well generated. I had a little issue with the subdir where they are written, and linked in index page but tis is another issue.... I'll try to debug this myself. Thanx.

**Comment by carteramandaj** [comment]
Great!  Happy to assist!
